project:
  type: book
  output-dir: docs
  pre-render: python build-chapters.py
  resources:
  - workflows/**
  - assets/presentations/**
  render:
  - index.qmd
  - gcp-setup.qmd
  - gcp-templates.qmd
  - mh1-processor.qmd
  - viirs-netpp.qmd
  - mur-sst.qmd
  - charm.qmd
  - erddap-cloud-migration-presentations.qmd
  - code-pages/charm/charm_data_process_functions.qmd
  - code-pages/charm/charm_dineof_functions.qmd
  - code-pages/charm/charm_helper_functions.qmd
  - code-pages/charm/charm_model_functions.qmd
  - code-pages/charm/config.qmd
  - code-pages/charm/control_charm_cron_v1.qmd
  - code-pages/charm/delpoy_job.qmd
  - code-pages/charm/dockerfile.qmd
  - code-pages/charm/entrypoint.qmd
  - code-pages/charm/for_Rrs_489_v4.qmd
  - code-pages/charm/for_Rrs_556_v4.qmd
  - code-pages/charm/for_bf_Rrs_489_v4.qmd
  - code-pages/charm/for_bf_Rrs_556_v4.qmd
  - code-pages/charm/for_bf_chlor_a_v4.qmd
  - code-pages/charm/for_chlor_a_v4.qmd
  - code-pages/charm/make_charm_cloud_v1.qmd
  - code-pages/charm/now_Rrs_489_v4.qmd
  - code-pages/charm/now_Rrs_556_v4.qmd
  - code-pages/charm/now_bf_Rrs_489_v4.qmd
  - code-pages/charm/now_bf_Rrs_556_v4.qmd
  - code-pages/charm/now_bf_chlor_a_v4.qmd
  - code-pages/charm/now_chlor_a_v4.qmd
  - code-pages/charm/requirements.qmd
  - code-pages/charm/viirs_L3.qmd
  - code-pages/mh1-processor/config.qmd
  - code-pages/mh1-processor/deploy_job.qmd
  - code-pages/mh1-processor/dockerfile.qmd
  - code-pages/mh1-processor/entrypoint.qmd
  - code-pages/mh1-processor/getMH1OceanColor_NRT.qmd
  - code-pages/mh1-processor/getMH1OceanColor_Sci.qmd
  - code-pages/mh1-processor/getMH1SST_NRT.qmd
  - code-pages/mh1-processor/getMH1SST_Sci.qmd
  - code-pages/mh1-processor/getMPIC_NRT.qmd
  - code-pages/mh1-processor/getMPIC_Sci.qmd
  - code-pages/mh1-processor/getMPOC_NRT.qmd
  - code-pages/mh1-processor/getMPOC_Sci.qmd
  - code-pages/mh1-processor/requirements.qmd
  - code-pages/mh1-processor/roylib.qmd
  - code-pages/mur-sst/Canny1.qmd
  - code-pages/mur-sst/Canny2.qmd
  - code-pages/mur-sst/CompMURmon.qmd
  - code-pages/mur-sst/CompMurAnomMon.qmd
  - code-pages/mur-sst/MUR41_MonProc.qmd
  - code-pages/mur-sst/MURanom1day.qmd
  - code-pages/mur-sst/calc_mur_fronts.qmd
  - code-pages/mur-sst/canny_lib.qmd
  - code-pages/mur-sst/config.qmd
  - code-pages/mur-sst/deploy_job.qmd
  - code-pages/mur-sst/dockerfile.qmd
  - code-pages/mur-sst/entrypoint.qmd
  - code-pages/mur-sst/mur_v41_downloader_dailyproc.qmd
  - code-pages/mur-sst/mur_v42_downloader.qmd
  - code-pages/mur-sst/requirements.qmd
  - code-pages/viirs-netpp/config.qmd
  - code-pages/viirs-netpp/control_viirs_netpp.qmd
  - code-pages/viirs-netpp/control_viirs_netpp_monthly.qmd
  - code-pages/viirs-netpp/deploy_job.qmd
  - code-pages/viirs-netpp/dockerfile.qmd
  - code-pages/viirs-netpp/entrypoint.qmd
  - code-pages/viirs-netpp/make_viirs_netpp.qmd
  - code-pages/viirs-netpp/make_viirs_netpp_monthly.qmd
  - code-pages/viirs-netpp/requirements.qmd
book:
  title: SWFSC ERDDAP Cloud Migration
  sidebar:
    logo: assets/logo.png
    title: ''
  chapters:
  - index.qmd
  - part: Setup
    chapters:
    - gcp-setup.qmd
    - gcp-templates.qmd
  - part: Workflows
    chapters:
    - mh1-processor.qmd
    - viirs-netpp.qmd
    - mur-sst.qmd
    - charm.qmd
  - part: Presentations
    chapters:
    - erddap-cloud-migration-presentations.qmd
  - part: 'Code: charm'
    chapters:
    - code-pages/charm/charm_data_process_functions.qmd
    - code-pages/charm/charm_dineof_functions.qmd
    - code-pages/charm/charm_helper_functions.qmd
    - code-pages/charm/charm_model_functions.qmd
    - code-pages/charm/config.qmd
    - code-pages/charm/control_charm_cron_v1.qmd
    - code-pages/charm/delpoy_job.qmd
    - code-pages/charm/dockerfile.qmd
    - code-pages/charm/entrypoint.qmd
    - code-pages/charm/for_Rrs_489_v4.qmd
    - code-pages/charm/for_Rrs_556_v4.qmd
    - code-pages/charm/for_bf_Rrs_489_v4.qmd
    - code-pages/charm/for_bf_Rrs_556_v4.qmd
    - code-pages/charm/for_bf_chlor_a_v4.qmd
    - code-pages/charm/for_chlor_a_v4.qmd
    - code-pages/charm/make_charm_cloud_v1.qmd
    - code-pages/charm/now_Rrs_489_v4.qmd
    - code-pages/charm/now_Rrs_556_v4.qmd
    - code-pages/charm/now_bf_Rrs_489_v4.qmd
    - code-pages/charm/now_bf_Rrs_556_v4.qmd
    - code-pages/charm/now_bf_chlor_a_v4.qmd
    - code-pages/charm/now_chlor_a_v4.qmd
    - code-pages/charm/requirements.qmd
    - code-pages/charm/viirs_L3.qmd
  - part: 'Code: mh1-processor'
    chapters:
    - code-pages/mh1-processor/config.qmd
    - code-pages/mh1-processor/deploy_job.qmd
    - code-pages/mh1-processor/dockerfile.qmd
    - code-pages/mh1-processor/entrypoint.qmd
    - code-pages/mh1-processor/getMH1OceanColor_NRT.qmd
    - code-pages/mh1-processor/getMH1OceanColor_Sci.qmd
    - code-pages/mh1-processor/getMH1SST_NRT.qmd
    - code-pages/mh1-processor/getMH1SST_Sci.qmd
    - code-pages/mh1-processor/getMPIC_NRT.qmd
    - code-pages/mh1-processor/getMPIC_Sci.qmd
    - code-pages/mh1-processor/getMPOC_NRT.qmd
    - code-pages/mh1-processor/getMPOC_Sci.qmd
    - code-pages/mh1-processor/requirements.qmd
    - code-pages/mh1-processor/roylib.qmd
  - part: 'Code: mur-sst'
    chapters:
    - code-pages/mur-sst/Canny1.qmd
    - code-pages/mur-sst/Canny2.qmd
    - code-pages/mur-sst/CompMURmon.qmd
    - code-pages/mur-sst/CompMurAnomMon.qmd
    - code-pages/mur-sst/MUR41_MonProc.qmd
    - code-pages/mur-sst/MURanom1day.qmd
    - code-pages/mur-sst/calc_mur_fronts.qmd
    - code-pages/mur-sst/canny_lib.qmd
    - code-pages/mur-sst/config.qmd
    - code-pages/mur-sst/deploy_job.qmd
    - code-pages/mur-sst/dockerfile.qmd
    - code-pages/mur-sst/entrypoint.qmd
    - code-pages/mur-sst/mur_v41_downloader_dailyproc.qmd
    - code-pages/mur-sst/mur_v42_downloader.qmd
    - code-pages/mur-sst/requirements.qmd
    - code-pages/mur-sst/roylib.qmd
  - part: 'Code: viirs-netpp'
    chapters:
    - code-pages/viirs-netpp/config.qmd
    - code-pages/viirs-netpp/control_viirs_netpp.qmd
    - code-pages/viirs-netpp/control_viirs_netpp_monthly.qmd
    - code-pages/viirs-netpp/deploy_job.qmd
    - code-pages/viirs-netpp/dockerfile.qmd
    - code-pages/viirs-netpp/entrypoint.qmd
    - code-pages/viirs-netpp/make_viirs_netpp.qmd
    - code-pages/viirs-netpp/make_viirs_netpp_monthly.qmd
    - code-pages/viirs-netpp/requirements.qmd
format:
  html:
    css: styles.css
    highlight-style: github
    link-external-icon: true
    number-sections: false
    sidebar:
      collapse-level: 2
      style: docked
    theme: cosmo
    toc: true
