---
title: "Dockerfile"
toc: false
page-layout: full
number-sections: false
---

[← Back to workflow](../../viirs-netpp.html)

Container environment for the VIIRS NetPP workflow.

::: {.code-shell}

```{.dockerfile}
{{< include ../../workflows/viirs-netpp/Dockerfile >}}
```

:::
