---
title: "Dockerfile"
toc: false
page-layout: full
number-sections: false
---

[← Back to workflow](../../mur-sst.html)

Container environment for the MUR SST workflow.

::: {.code-shell}

```{.dockerfile}
{{< include ../../workflows/mur-daily-workflows/Dockerfile >}}
```

:::
