---
title: "Dockerfile"
toc: false
page-layout: full
number-sections: false
---

[← Back to workflow](../../charm.html)

Container environment for the CHARM workflow.

::: {.code-shell}

```{.dockerfile}
{{< include ../../workflows/charm/Dockerfile >}}
```

:::
